network:
  rpc_endpoints:
    - "https://api.mainnet-beta.solana.com"
  max_retries: 3
  timeout: 30

trading:
  position_size_sol: 0.1
  max_holdings: 5
  slippage:
    buy: 0.01
    sell: 0.01
  min_liquidity: 1000
  min_volume: 100
  take_profit: 0.03
  stop_loss: 0.02
  dex_sources:
    - "raydium"
    - "jupiter"
  
  monitor_settings:
    check_interval: 1
    price_update: 5
    max_age: 60

performance:
  memory_limit_mb: 512
  max_latency_ms: 1000
  min_execution_speed_ms: 100

wallet:
  address: "5SQLc47TxVL6dsG5hwYt7t4gnrshhTJd17u4gcR1UPPQLQ8SEZLBUndj5EGnf75ZtgA8GrBxQ84WExDgH6apPr2N"
  type: "phantom"
  mode: "active"
